name: CI

on:
  schedule:
    - cron: '0 12 * * *'
  push:

jobs:

  # Run tests and publish amd64
  build_amd64:
    name: Run tests and publish amd64
    runs-on: buildjet-8vcpu-ubuntu-2204
    concurrency:
      group: ${{ github.ref }}-amd64
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: just build-amd64
      - name: Push image to Docker hub only on main or tag (release) but not on schedule
        if: (github.ref_name == 'main' || startsWith(github.ref, 'refs/tags')) && github.event_name != 'schedule'
        run: just push-amd64

  # Run tests and publish aarch64
  build_aarch64:
    name: Run tests and publish aarch64
    runs-on: buildjet-8vcpu-ubuntu-2204-arm
    concurrency:
      group: ${{ github.ref }}-aarch64
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: just build-arm64
      - name: Push image to Docker hub only on main or tag (release) but not on schedule
        if: (github.ref_name == 'main' || startsWith(github.ref, 'refs/tags')) && github.event_name != 'schedule'
        run: just push-arm64

  # publish manifest combining aarch64 and amd64 images
  publish_manifest:
    name: Build and Publish Manifest to Dockerhub
    runs-on: ubuntu-latest
    needs: [build_amd64, build_aarch64]
    if: (github.ref_name == 'main' || startsWith(github.ref, 'refs/tags')) && github.event_name != 'schedule'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v1
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: just publish-manifest
