name: CI

on:
  push:
  release:
    types: [published]

jobs:
  
  # build allways
  build:
    name: Build allways and publish on release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build
        run: make build
      - name: build
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          make publish
